pipelines:
  - name: sanity_TriggerPipeline_Parent
    steps:
      - name: Trigger_Pipeline_sanity_check
        type: TriggerPipeline
        configuration:
          pipelineName: sanity_TriggerPipeline_Child
          stepName: sanity_EnvironmentVariable_stepVariable_Check
          integrations:
            - name: sanity_platform
        
        execution:
          onStart:
            - echo "starting"
            - set_trigger_payload stepVariables "stepParam=true"
            - set_trigger_payload pipelineVariables "pipelineParam1=true" "pipelineParam2=Hello_World" "parentStepIDSet=${step_id}"

          onSuccess:
            - echo "Job completed successfully"
            - echo "${nested_run_status}"
            - |
              if [ "$nested_run_status" != "success" ]; then
              exit 1
              fi
            - echo "${nested_run_number}"
            - |
              if [ -z "$nested_run_number" ]; then
              exit 1
              fi
            - echo "${nested_run_duration_seconds}"
            - |
              if [ -z "$nested_run_duration_seconds" ]; then
              exit 1
              fi
            - echo "${nested_run_url}"
            - |
              if [ -z "$nested_run_url" ]; then
              exit 1
              fi

          onFailure:
            - echo "Job failed"

          onComplete:
            - echo "Parent pipeline execution over"



  - name: sanity_TriggerPipeline_Child
    steps:
      - name: sanity_EnvironmentVariable_stepVariable_Check
        type: Bash
        execution:
          onExecute:
            - echo "${stepParam}"
            - |
              if [ "$stepParam" != "true" ]; then
              exit 1
              fi
            - echo "${pipelineParam1}"
            - |
              if [ "$pipelineParam1" != "true" ]; then
              exit 1
              fi
            - echo "${pipelineParam2}"
            - |
              if [ "$pipelineParam2" != "Hello_World" ]; then
              exit 1
              fi
            - echo "${parentStepIDSet}"
            - |
              if [ -z "$parentStepIDSet" ]; then
              exit 1
              fi

      - name: sanity_EnvironmentVariable_pipelineVariable_Check
        type: Bash
        configuration:
          inputSteps:
            - name: sanity_EnvironmentVariable_stepVariable_Check
        execution:
          onExecute:
            - echo "${stepParam}"
            - |
              if [ -n "$stepParam" ]; then
              exit 1
              fi
            - echo "${pipelineParam1}"
            - |
              if [ "$pipelineParam1" != "true" ]; then
              exit 1
              fi
            - echo "${pipelineParam2}"
            - |
              if [ "$pipelineParam2" != "Hello_World" ]; then
              exit 1
              fi
            - echo "${parentStepIDSet}"
            - |
              if [ -z "$parentStepIDSet" ]; then
              exit 1
              fi

      - name: ParentEnvironmentVariable_check
        type: Bash
        configuration:
          inputSteps:
            - name: sanity_EnvironmentVariable_pipelineVariable_Check
        execution:
          onExecute:
            - echo "${parent_step_id}"
            - |
              if [ "$parent_step_id" != "${parentStepIDSet}" ]; then
              exit 1
              fi
            - echo "${parent_step_name}"
            - |
              if [ "$parent_step_name" != "Trigger_Pipeline_sanity_check" ]; then
              exit 1
              fi
            - echo "${parent_run_id}"
            - |
              if [ -z "$parent_run_id" ]; then
              exit 1
              fi
            - echo "${parent_run_number}"
            - |
              if [ -z "$parent_run_number" ]; then
              exit 1
              fi
            - echo "${parent_step_url}"
            - |
              if [ -z "$parent_step_url" ]; then
              exit 1
              fi
