resources:
  - name: myRepoResource
    type: GitRepo
    configuration:
      gitProvider: int_github
      path: kanishkguptagit/JFrogTestreports
      branches:
        include: master
pipelines:
  - name: TestElement
    steps:
      - name: TestElement_1
        type: Bash
        configuration:
          inputResources:
            - name: myRepoResource
        execution:
          onExecute:
            - save_tests "$res_myRepoResource_resourcePath/tests/junit/test_results_example_1.xml"
