resources:
  - name: myRepoResource
    type: GitRepo
    configuration:
      gitProvider: int_github
      path: kanishkguptagit/JFrogTestreports
      branches:
        include: master

  - name: myPropertyBag
    type: PropertyBag
    configuration:
      STEP_ID: value

pipelines:
  - name: sanity_TestReports
    steps:
      - name: GenerateReports
        type: Bash
        configuration:
          inputResources:
            - name: myRepoResource
          outputResources:
            - name: myPropertyBag
        execution:
          onExecute:
            - echo "${step_id}"
            - save_tests "$res_myRepoResource_resourcePath/tests/junit/test_results_example_1.xml"
            - write_output myPropertyBag "STEP_ID=${step_id}"
            

      - name: verifyReports
        type: Bash
        configuration:
          integrations:
            - name: sanity_platform
          inputResources:
            - name: myPropertyBag
          inputSteps:
            - name: GenerateReports
        execution:
          onExecute:
            - echo "${res_myPropertyBag_STEP_ID}"
            - echo "${int_sanity_platform_accessToken}"
            - echo "${int_sanity_platform_url}"
            - |
              curl -o testReportOutput_${res_myPropertyBag_STEP_ID}.tar.gz --location 'https://stg-repo.jfrog.info/pipelines/api/v1/steps/${res_myPropertyBag_STEP_ID}/stepTestReports' --header 'Authorization: Bearer ${int_sanity_platform_accessToken}'
            - ls -la
            - file testReportOutput_${res_myPropertyBag_STEP_ID}.tar.gz
            - cat testReportOutput_${res_myPropertyBag_STEP_ID}.tar.gz
            - tar -xzvf testReportOutput_${res_myPropertyBag_STEP_ID}.tar.gz
            - cat tests/testReports/testReport.json

